name: colibri
description: Colibri


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

flutter_localizations:
    sdk: flutter

dependencies:
  flutter:
    sdk: flutter
  # for functional programming
  dartz: ^0.10.1
  # for api calls
  dio: ^4.0.4 
  google_fonts: ^2.3.1 
  flutter_hooks: ^0.18.2 
  flutter_screenutil: ^5.4.0+1
  is_first_run: ^1.0.0
  rxdart: ^0.27.3 
  flutter_svg: ^1.0.3
  flutter_bloc: ^8.0.1
  sized_context: ^1.0.0+1
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  equatable: ^2.0.3
  injectable: ^1.5.3
  get_it: ^7.2.0 
  another_flushbar: ^1.10.28
  font_awesome_flutter: ^10.1.0
  cached_network_image: ^3.2.0
  image_picker: ^0.8.4+11 
  emoji_picker_flutter: ^1.1.2
  flutter_animated_dialog: ^2.0.1 
  giphy_picker: ^2.0.0
  intl: ^0.17.0
  auto_route: ^4.0.1
  photo_view: ^0.13.0
  file_picker: ^4.5.1 
  flutter_cache_manager: ^3.3.0
  restart_app: ^1.1.0+1
  path_provider: ^2.0.9 
  video_compress: ^3.1.0 
  video_player: ^2.4.5
  flutter_easyloading: ^3.0.3
  palette_generator: ^0.3.3+2
  photo_manager: ^2.2.1
  permission_handler: ^10.0.0
  percent_indicator: ^4.2.2
  better_player: ^0.0.83
  audio_video_progress_bar: ^0.10.0
  flutter_login_facebook: ^1.4.1
  flutter_local_notifications: ^9.9.0
  linear_progress_bar: ^1.1.0
  google_sign_in: ^5.4.0
  infinite_scroll_pagination: ^3.1.0 
  auto_size_text: ^3.0.0-nullsafety.0
  faker: ^2.0.0 
  youtube_player_flutter: ^8.1.0
  native_device_orientation: ^1.0.0
  mime: ^1.0.1
  video_thumbnail: ^0.5.3
  velocity_x: ^3.4.0
  timelines: ^0.1.0 
  url_launcher: ^6.0.20
  animations: ^2.0.2 
  flutter_linkify: ^5.0.2 
  share: ^2.0.4
  webview_flutter: ^3.0.1 
  shared_preferences: ^2.0.13
  visibility_detector: ^0.3.3
  screenshot: ^1.2.3
  cupertino_icons: ^1.0.4

  material_floating_search_bar: ^0.3.7
  image_cropper: ^3.0.0
  flutter_image_compress: ^1.1.0 
  #Discontinued
  file_utils: ^1.0.1
  keyboard_actions: ^3.4.7
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  # TODO Return this after fixing error
  flutter_awesome_select: ^6.5.0
  remove_emoji: ^0.0.6 
  modal_bottom_sheet: ^2.0.1 
  easy_localization: ^3.0.0  
  html: ^0.15.0
  simple_url_preview: ^3.0.1 
  camera: ^0.10.0+1
  flutter_keyboard_visibility: ^5.2.0
  collection: ^1.15.0-nullsafety.4
  string_validator: ^0.3.0
  package_info_plus: ^1.4.2

dev_dependencies:
  dependency_validator: ^3.1.2
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.8
  flutter_launcher_icons: ^0.10.0
  change_app_package_name: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "images/logo.png"
  image_path_ios:  "images/ios-logo.jpg"
  min_sdk_android: 21


flutter:
  uses-material-design: true

  
  assets:
    - images/
    - images/png_image/
    - assets/translations/


  fonts:
    - family: Poppins
      fonts: 
        - asset: fonts/Poppins-Regular.ttf
          weight: 200
        - asset: fonts/Poppins-Medium.ttf
          weight: 400  
        - asset: fonts/Poppins-Bold.ttf
          weight: 600
    - family: Inter
      fonts: 
        - asset: fonts/Inter-Regular.ttf
          weight: 200
        - asset: fonts/Inter-Medium.ttf
          weight: 400  
        - asset: fonts/Inter-Bold.ttf
          weight: 600
    - family: Campton
      fonts:
        - asset: fonts/Campton-Light.ttf
          weight: 200
        - asset: fonts/Campton-Medium.ttf
          weight: 400
        - asset: fonts/Campton-Bold.ttf
          weight: 600
    - family: CeraPro
      fonts:
        - asset: fonts/CeraPro-Regular.ttf
          weight: 200
        - asset: fonts/CeraPro-Medium.ttf
          weight: 400
        - asset: fonts/CeraPro-Bold.ttf
          weight: 600


          